services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mysql-database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql: